#!/bin/bash
source ~/.bashrc
gitanoaddfile bin/*
gitanoaddfile bin/*/*
gitanoaddfile bin/*/*/*
gitanoaddfile bin/*/*/*/*
gitanoaddfile dev/*
gitanoaddfile dev/*/*
gitanoaddfile dev/*/*/*
gitanoaddfile dev/*/*/*/*
gitanoaddfile dist/*
gitanoaddfile dist/*/*
gitanoaddfile dist/*/*/*
gitanoaddfile dist/*/*/*/*
gitanoaddfile docs/*
gitanoaddfile docs/*/*
gitanoaddfile docs/*/*/*
gitanoaddfile docs/*/*/*/*
gitanoaddfile i18n/*
gitanoaddfile i18n/*/*
gitanoaddfile i18n/*/*/*
gitanoaddfile i18n/*/*/*/*
gitanoaddfile scrap/*
gitanoaddfile scrap/*/*
gitanoaddfile scrap/*/*/*
gitanoaddfile scrap/*/*/*/*
gitanoaddfile src/*
gitanoaddfile src/*/*
gitanoaddfile src/*/*/*
gitanoaddfile src/*/*/*/*
gitanoaddfile test/*
gitanoaddfile test/e2e/integration/*
gitanoaddfile test/e2e/integration/*/*
gitanoaddfile test/e2e/integration/*/*/*
gitanoaddfile test/e2e/integration/*/*/*/*
gitanoaddfile test/e2e/*/*
gitanoaddfile test/unit/*
gitanoaddfile test/unit/*/*
gitanoaddfile test/unit/*/*/*
gitanoaddfile test/unit/*/*/*/*
gitanoaddfile scrap/*
gitanoaddfile scrap/*/*
gitanoaddfile scrap/*/*/*
gitanoaddfile scrap/*/*/*/*
gitanoaddfile *
gitanopush