gantt
dateFormat  YYYY-MM-DD
title Temporización
section Contrato
Definición del feature: s1,2019-01-01, 1d
Aperture del feature: s2, after s1, 1d
section Diseño
Diseño de solución: s3, after s2, 4d
Diseño de implementación: s4, after s3, 4d
section Testeo
Especificación de uso: s5, after s4, 2d
Especificación de unidad: s6, after s5, 2d
section Codificación
Superación de especificaciones: s7, after s6, 6d
section Documentación
Documentación de la feature: s8, after s7, 3d
section Integración
Subir la feature: s9, after s8, 1d
Mezclar branca: s10, after s9, 2d
Cerrar branca: s11, after s10, 1d